### ISSUE TITLE
画像の位置

### ISSUE THREAD

**Issue by organic-nailer** [190ikp/basic-experiment-report-b2#2]
# 問題

表番号つけると画像がページの最上部に移動しちゃいます

理想
![image](https://user-images.githubusercontent.com/31440714/81492749-5cc00980-92d5-11ea-835b-78f8145969fd.png)

出力
![image](https://user-images.githubusercontent.com/31440714/81492772-9e50b480-92d5-11ea-827c-f76507ab916b.png)

環境は
Ubuntu 18.04 (WSL) + Pandoc 2.1.3 + TeXLive2020

# 解決策
多分これ
https://stackoverflow.com/questions/49482221/pandoc-markdown-to-pdf-image-position

template.texの適当な部分に追加したら改善しました

```TeX
\usepackage{float}
\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}
```

**Comment by 190ikp** [comment]
Pandocの仕様です．諦めてください...
`here`パッケージを使うことで~~無理やり~~解決できます．
template.mdにはYAMLメタデータブロックに書いてあるのでそのまま使えます．
```
---
documentclass: ltjsarticle
header-includes:
  - \usepackage{here}
---

\begin{figure}[H]
\hypertarget{fig:example}{%
\centering
\includegraphics[width=\textwidth,height=60mm]{example.jpg}
\caption{いい感じの図}\label{fig:example}
}
\end{figure}
```
任意の場所にこんな感じで書くとうまく埋め込めるはずです．
たまにビルドエラーを吐いて失敗してしまうことがありますが，その場合はlatexコマンドで埋め込む必要のない画像をmarkdownの書式で埋め込んであげると直る場合があります．

(普通に埋め込む場合もそうですが) デフォルトだと用紙に対して結構大きなサイズで埋め込まれてしまうので，サイズ調節して埋め込むことをおすすめします．
height=60mmくらいだとちょうどいい感じです．

**Comment by 190ikp** [comment]
> たまにビルドエラーを吐いて失敗してしまうことがありますが，

これ`header-includes`に`\usepackage{graphicx}`を追加することで解決できることがわかった
